server:
  port: 8050
spring:
  application:
    name: testddd
  thymeleaf:
    content-type: text/html
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/distributor?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
